[package]
name = "valence_playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[dependencies]
rand = "0.8"
valence_new = { git = "https://github.com/valence-rs/valence", branch = "ecs_rewrite" }