[tasks.nixos_build]
script = '''
sudo systemctl stop valence_playground.service
cargo build --release --no-default-features --features minecraft
cp target/release/valence_playground bin/valence_playground
sudo systemctl start valence_playground.service
'''

[tasks.r]
command = "cargo"
args = ["run"]

[tasks.no_gui]
command = "cargo"
args = ["run", "--no-default-features", "--features", "minecraft"]