[tasks.nixos_build]
script = '''
git pull
sudo systemctl stop valence_playground.service
cargo build --release --no-default-features --features minecraft,online
cp target/release/valence_playground bin/valence_playground
sudo systemctl start valence_playground.service
echo "Build and started"
'''

[tasks.r]
command = "cargo"
args = ["run"]

[tasks.no_gui]
command = "cargo"
args = ["run", "-r", "--no-default-features", "--features", "minecraft"]