edition = "2021"
unstable_features = true
condense_wildcard_suffixes = true
fn_single_line = true
format_code_in_doc_comments = true
format_strings = true
imports_granularity = "Crate"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true